name: the_color_code
version: 0.0.1
description: A quiz for the Hartman Personality Profile done with Dart and Flutter
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:       # Required for every Flutter project
    sdk: flutter # Required for every Flutter project
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter # Required for a Flutter project that includes tests

flutter:
  uses-material-design: true # Required if you use the Material icon font